language: python

python:
    - "3.6"

sudo: false

env:
    - TOX_ENV=py36
    - TOX_ENV=flake8

install:
    - pip install tox

script:
    - tox -e $TOX_ENV

after_success:
    - pip install codecov
    - codecov -e TOX_ENV

notifications:
    email: false
