version: '2'
services:
    redis:
        image: library/redis:3.2.1
        ports:
            - "6379:6379"
    postgres:
        image: library/postgres:9.5.3
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=devel
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=manager
