# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import registers.receipts


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_auto_20170429_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(blank=True, default=registers.receipts.timezone_now),
        ),
    ]
